### PR TITLE
init model

### PR DESCRIPTION
**Pull request by gitlinhleqtgh**
init model!

### CODE REVIEW

**Comment by gitlinhleqtgh** [comment]
ready

**Comment by gitlinhleqtgh** [comment]
commented

**Comment by vanvtt-0952** [comment]
commented
fix conflict đi nhé

**Comment by gitlinhleqtgh** [comment]
ready

**Comment by gitlinhleqtgh** [comment]
ready

**Comment by gitlinhleqtgh** [comment]
ready

**Pull request merged**
